const ITEMS = [
  { term: "DNS Server", definition: "Übersetzt menschenlesbare Domainnamen in IP-Adressen." },
  { term: "DHCP Server", definition: "Weist Geräten automatisch IP-Adressen und Netzwerk-Konfigurationsparameter zu." },
  { term: "Router", definition: "Leitet Datenpakete zwischen verschiedenen Netzwerken weiter." },
  { term: "nslookup", definition: "Netzwerkbefehl zum Durchführen von DNS-Abfragen." },
  { term: "ping", definition: "Testet die Erreichbarkeit eines Hosts mit ICMP-Echo-Anfragen." },
  { term: "tracert", definition: "Zeigt den Weg und Hops eines Datenpakets zum Ziel." },
  { term: "route print", definition: "Windows-Befehl zum Anzeigen der Routing-Tabelle." },
  { term: "Active Directory", definition: "Microsoft-Verzeichnisdienst zur zentralen Verwaltung von Benutzern und Ressourcen." },
  { term: "IMAP", definition: "E-Mail-Protokoll für serverbasierten Zugriff, Ports 143/993." },
  { term: "POP3", definition: "E-Mail-Protokoll zum Herunterladen von Mails, Ports 110/995." },
  { term: "SMTP", definition: "Protokoll zum Senden von E-Mails, Ports 25/587/465." },
  { term: "SSH", definition: "Secure Shell zur sicheren Fernsteuerung, Port 22." },
  { term: "FTP", definition: "File Transfer Protocol, Ports 20/21." },
  { term: "HTTP", definition: "Webprotokoll über Port 80, unverschlüsselt." },
  { term: "HTTPS", definition: "Webprotokoll über Port 443, verschlüsselt via SSL/TLS." },
  { term: "Fetchmail", definition: "Dienstprogramm zum Abrufen von E-Mails von Remote-Mailservern." },
  { term: "TCP", definition: "Verbindungsorientiertes Protokoll mit Fehlerkorrektur." },
  { term: "UDP", definition: "Verbindungsloses Protokoll ohne Garantie für Zustellung." },
  { term: "VPN", definition: "Verschlüsselt Internetverbindungen über einen sicheren Tunnel." },
  { term: "Proxy", definition: "Server als Vermittler zwischen Client und Internet." },
  { term: "Kernel", definition: "Zentraler Bestandteil des Betriebssystems, verwaltet Hardware/Software." },
  { term: "RAID 0", definition: "Striping – Leistung, aber keine Redundanz." },
  { term: "RAID 1", definition: "Mirroring – volle Datensicherheit, halber Speicher." },
  { term: "RAID 5", definition: "Striping mit Parität, benötigt min. 3 Platten." },
  { term: "RAID 6", definition: "Wie RAID 5, aber mit doppelter Parität (2 Plattenausfälle)." },
  { term: "RAID 10", definition: "Kombination aus RAID 0 + 1 (Striping + Mirroring)." },
  { term: "SMB", definition: "Server Message Block – Dateifreigabenetzwerkprotokoll." },
  { term: "SMB Port", definition: "Port 445 TCP." },
  { term: "SMB NetBios", definition: "Alter Port 139 TCP." },
  { term: "telnet", definition: "Textbasierte TCP-Verbindung, Test von Ports." },
  { term: "telnet Syntax", definition: "telnet <Hostname> <Port>" },
  { term: "NTP", definition: "Network Time Protocol – Zeitsynchronisation." },
  { term: "SIP", definition: "Session Initiation Protocol – VoIP-Signalisierung." },
  { term: "ICMP", definition: "Internet Control Message Protocol – Fehler- und Diagnosemeldungen." },
  { term: "RDP", definition: "Remote Desktop Protocol für Windows-Remotezugriff." },
  { term: "VLAN", definition: "Virtuelle Netzsegmente für bessere Sicherheit und Verwaltung." },
  { term: "SNMP", definition: "Simple Network Management Protocol – Monitoring von Geräten." },
  { term: "Subnetz", definition: "Unterteilung eines Netzwerks per Subnetzmaske." },
  { term: "Firewall", definition: "Filtert und blockiert Datenverkehr anhand von Regeln." },
  { term: "NAS", definition: "Network Attached Storage – netzwerkgebundenes Speichergerät." },
  { term: "SAN", definition: "Storage Area Network – dediziertes Hochgeschwindigkeits-Speichernetz." },
  { term: "LDAP", definition: "Lightweight Directory Access Protocol für Verzeichnisdienste." },
  { term: "BIOS/UEFI", definition: "Firmware zum Initialisieren der Hardware beim Start." },
  { term: "GPO", definition: "Group Policy Object – zentrale Windows-Richtlinien." },
  { term: "Netzlaufwerk verbinden", definition: "Per UNC, GPO oder Login-Skript möglich." },
  { term: "Domänencontroller", definition: "Server mit Active Directory Rolle." },
  { term: "Catchall Mailbox", definition: "Postfach, das alle Mails einer Domain empfängt." }
];
